apiVersion: v1
kind: Service
metadata:
  name: firstangular-service
  labels:
    app: firstangular-app
spec:
  type: LoadBalancer
  selector:
    app: firstangular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
