apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstangular-deployment
  labels:
    app: firstangular-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstangular-app
  template:
    metadata:
      labels:
        app: firstangular-app
    spec:
      containers:
      - name: firstappangular-container
        image: pcsathish1/first-angular-app:2.0
        ports:
        - containerPort: 80
